// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjhHi0-MwUYucgLqD1pDmWdHBDMPaYkw',
    appId: '1:838019101943:web:4043f8cac1792933638ff2',
    messagingSenderId: '838019101943',
    projectId: 'easyride-94dc3',
    authDomain: 'easyride-94dc3.firebaseapp.com',
    storageBucket: 'easyride-94dc3.firebasestorage.app',
    measurementId: 'G-9YYLDC156X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU6yTdRxhdACvqYOAyoyA7h_6LItKYjko',
    appId: '1:838019101943:android:c7055eece9404fb7638ff2',
    messagingSenderId: '838019101943',
    projectId: 'easyride-94dc3',
    storageBucket: 'easyride-94dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9cp7SN7d1GKrKx8BpOjc10CQugJgG_Mg',
    appId: '1:838019101943:ios:3bf5a5af908e933e638ff2',
    messagingSenderId: '838019101943',
    projectId: 'easyride-94dc3',
    storageBucket: 'easyride-94dc3.firebasestorage.app',
    iosBundleId: 'com.aytech.easyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9cp7SN7d1GKrKx8BpOjc10CQugJgG_Mg',
    appId: '1:838019101943:ios:0e6450f7a79cb933638ff2',
    messagingSenderId: '838019101943',
    projectId: 'easyride-94dc3',
    storageBucket: 'easyride-94dc3.firebasestorage.app',
    iosBundleId: 'com.example.easyRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtjhHi0-MwUYucgLqD1pDmWdHBDMPaYkw',
    appId: '1:838019101943:web:da80837e3c50b0de638ff2',
    messagingSenderId: '838019101943',
    projectId: 'easyride-94dc3',
    authDomain: 'easyride-94dc3.firebaseapp.com',
    storageBucket: 'easyride-94dc3.firebasestorage.app',
    measurementId: 'G-FG77RV4F3X',
  );
}
